### PR TITLE
Larger Scale alerting

### PR DESCRIPTION
**Pull request by matthew-lucidchart**
Tried to use tattle for work, but didn't get very far. We have too many alerts, subscriptions, and servers running. These adjustments make running the processor better.

### CODE REVIEW

**Comment by g76r** [comment]
@matthew-lucidchart seems nice ! but I need to test this before merging (@draco2003 has just transfered the project to me and despite the age of your pull request I need a few time)

do you still use use tattle these days ?

**Comment by matthew-lucidchart** [comment]
No. We stopped using tattle pretty quickly after starting. Sorry

**Comment by g76r** [comment]
thanks !

**Comment by g76r** [comment]
I've just merged some of your contributions but left some of them apart.

Here is a explanation of the choices I've done. I'm of course open to any further discussion:
- ignore sublime files: since not every one use sublime text, I think it should be better to put that kind of patterns in .git/info/exclude or even use git config --global core.excludesfile if you often use sublime text.
- handle null values in check processing / skip processing of checks with missing or null values: although convenient to avoid false positives, ignoring null values can mean ignoring failures, therefore the change may be worse than current behaviour (I would change my mind happily if you or someone else interested in this change explain why it is better)
- use mutex for processing: I prefer the protection against double execution of the processor to be handled by the scheduler which triggers it, because holding a lock in the database could lead to dandling locks (I would change my mind if the feature was optional so that only people using a dumb scheduler - such as cron - would enable it if they want)

**Pull request closed without merging**
